import type { ErrorCode } from '../types';

export const API_ERROR_CODES = {
  CHALLENGE_NOT_FOUND: 'CHALLENGE_NOT_FOUND',
  CHALLENGE_NOT_AVAILABLE: 'CHALLENGE_NOT_AVAILABLE',
  QUIZ_ALREADY_COMPLETED: 'QUIZ_ALREADY_COMPLETED',
  ANSWER_ALREADY_SUBMITTED: 'ANSWER_ALREADY_SUBMITTED',
  QUESTION_NOT_IN_ATTEMPT: 'QUESTION_NOT_IN_ATTEMPT',
  OPTION_NOT_IN_QUESTION: 'OPTION_NOT_IN_QUESTION',
  NOT_ALL_QUESTIONS_ANSWERED: 'NOT_ALL_QUESTIONS_ANSWERED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const satisfies Record<ErrorCode, ErrorCode>;
